### ISSUE TITLE
Frequent crashing

### ISSUE THREAD

**Issue by PaulPorthouse** [Algorithman/SoundCenSe#13] opened 2017-01-19 07:10 UTC
Hi

I have been encountering frequent crashes of the application with the following error in the log (this is the entire log for this session)
```
2017-01-19 06:47:05.1415|WARN|SoundCenSeGTK.MainClass|Checking dll in registry
2017-01-19 06:47:07.1915|WARN|SoundCenSeGTK.SoundsXML|Include listing tag without valid 'filePathAndName' attribute encountered (make sure it ends in '.xml'!).
2017-01-19 06:54:00.8535|ERROR|SoundCenSeGTK.PackDownloader|File http://df.zweistein.cz/soundsense/soundpack/autoUpdater.xml had wrong checksum (45328223b0bc4983941a7eef45e6721821a0207c<->b67a8d1a88a896bf3d1677d41037f17fa08e8170
2017-01-19 06:54:52.6242|WARN|missing|Loaded region8, Ecamo Alino (The Universes of Dawn) at coordinates (45,42)
2017-01-19 06:54:52.9537|WARN|missing|Loaded the fortress Erusharzes (Handleknight), colonized by the group Bithsestiden (The Triangular Paddle) of the civilization Catten Om (The Channels of Crushing).
2017-01-19 07:02:48.6198|ERROR|SoundCenSeGTK.LogFileListener|Exception while reading gamelog
2017-01-19 07:02:48.6228|ERROR|SoundCenSeGTK.LogFileListener|System.NullReferenceException: Object reference not set to an instance of an object.
   at SoundCenSeGTK.FmodChannelPool.IsSoundPlaying(String filename)
   at SoundCenSeGTK.fmodPlayer.PlaySound(SoundSoundFile sf, String channel, Single volume, Boolean mute)
   at SoundCenSeGTK.fmodPlayer.Play(ISound sound, Int64 x, Int64 y, Int64 z)
   at SoundCenSeGTK.SoundProcessor.ProcessLine(Object sender, GamelogEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at SoundCenSeGTK.LogFileListener.OnLogfileEvent(String line)
   at SoundCenSeGTK.LogFileListener.Tick()
```

Many thanks, and keep up the good work, as I hate having to install Java just for Soundsense.

**Comment by Algorithman** [comment] 2017-02-14 19:14
Sorry for the late response. 

Which OS do you work on? Seems to me SoundCense could not read from the gamelog.txt for some reason. Is it on a network share?

**Comment by PaulPorthouse** [comment] 2017-02-14 19:18
Hi

No worries. I use Windows 10, and there is isn't anything special. It's installed in the standard way via the LNP to a directory on my C drive. 

I did notice the NRE on the log file, and was wondering if it could be locked at the instance it's trying to read from it?

Anyway, thanks for looking, and let me know if you need more info.

**Comment by thmsndk** [comment] 2017-07-08 16:54
I am also running Windows 10, and is experiencing a lot of crashes with the following entry in the log.txt

> 2017-07-08 18:46:45.4893|ERROR|SoundCenSeGTK.LogFileListener|Exception while reading gamelog
2017-07-08 18:46:45.4893|ERROR|SoundCenSeGTK.LogFileListener|System.NullReferenceException: Object reference not set to an instance of an object.
   at SoundCenSeGTK.FmodChannelPool.IsSoundPlaying(String filename)
   at SoundCenSeGTK.fmodPlayer.PlaySound(SoundSoundFile sf, String channel, Single volume, Boolean mute)
   at SoundCenSeGTK.fmodPlayer.Play(ISound sound, Int64 x, Int64 y, Int64 z)
   at SoundCenSeGTK.SoundProcessor.ProcessLine(Object sender, GamelogEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at SoundCenSeGTK.LogFileListener.OnLogfileEvent(String line)
   at SoundCenSeGTK.LogFileListener.Tick()

**Comment by Algorithman** [comment] 2017-07-08 18:29
https://github.com/Algorithman/SoundCenSe/releases/tag/1.4.2CrashDebug
Pls try, i've got time today, so i might be able to fix it.

**Comment by PaulPorthouse** [comment] 2017-07-08 18:31
@Algorithman 

Apologies, I can't as I'm busy today, and I currently don't have Dwarf Fortress installed.

**Comment by Algorithman** [comment] 2017-07-08 18:32
np Paul, thmsndk might have time

**Comment by thmsndk** [comment] 2017-07-08 18:34
@Algorithman Just installed it, now I just gotta wait for it to crash xD

**Comment by Algorithman** [comment] 2017-07-08 18:36
I added some NULL checks, if you got a few more FATAL entries in the logfile, pls tell me

**Comment by thmsndk** [comment] 2017-07-08 18:38
@Algorithman When you say FATAL entries, do you mean ERROR?

**Comment by Algorithman** [comment] 2017-07-08 18:38
no, they should be labeled FATAL

**Comment by Algorithman** [comment] 2017-07-08 18:40
But it also could be that the error is completely gone, since i changed the way i gather the values i have to check.

**Comment by thmsndk** [comment] 2017-07-08 18:43
Fair enough, the previous error I had in the log was a nullreference being logged as ERROR, so your null checks should catch thoose, it was in the IsSoundPlayingCheck that something went wrong after all :) 

I've set up notepad++ to watch the log file during play, i'll post again if it crashes or something odd happens in the log :)

**Comment by Algorithman** [comment] 2017-07-08 18:43
ty

**Comment by thmsndk** [comment] 2017-07-08 18:46
@Algorithman 

` 2017-07-08 20:43:36.0960|FATAL|SoundCenSeGTK.FmodChannelPool|sf.SoundSoundFile.SoundFile is NULL while looking for F:\Games\Dwarf Fortress\PeridexisErrant's Starter Pack 0.43.05-r07\LNP\Utilities\Soundsense\packs\battle\gore/tearheavygore5.mp3
2017-07-08 20:43:36.1165|FATAL|SoundCenSeGTK.FmodChannelPool|sf.SoundSoundFile.SoundFile is NULL while looking for F:\Games\Dwarf Fortress\PeridexisErrant's Starter Pack 0.43.05-r07\LNP\Utilities\Soundsense\packs\battle\hit/ranged/arrowHit04.mp3
2017-07-08 20:43:36.1385|WARN|missing|The force pulls the head!
2017-07-08 20:43:36.5470|FATAL|SoundCenSeGTK.FmodChannelPool|sf.SoundSoundFile.SoundFile is NULL while looking for F:\Games\Dwarf Fortress\PeridexisErrant's Starter Pack 0.43.05-r07\LNP\Utilities\Soundsense\packs\battle\gore/tearheavygore9.mp3
2017-07-08 20:43:36.5700|FATAL|SoundCenSeGTK.FmodChannelPool|sf.SoundSoundFile.SoundFile is NULL while looking for F:\Games\Dwarf Fortress\PeridexisErrant's Starter Pack 0.43.05-r07\LNP\Utilities\Soundsense\packs\battle\hit/ranged/arrowHit08.mp3
2017-07-08 20:43:37.4772|FATAL|SoundCenSeGTK.FmodChannelPool|sf.SoundSoundFile.SoundFile is NULL while looking for F:\Games\Dwarf Fortress\PeridexisErrant's Starter Pack 0.43.05-r07\LNP\Utilities\Soundsense\packs\battle\gore/glance1.mp3
2017-07-08 20:43:37.5122|FATAL|SoundCenSeGTK.FmodChannelPool|sf.SoundSoundFile.SoundFile is NULL while looking for F:\Games\Dwarf Fortress\PeridexisErrant's Starter Pack 0.43.05-r07\LNP\Utilities\Soundsense\packs\battle\hit/ranged/arrowHit01.mp3
2017-07-08 20:43:37.5367|WARN|missing|The force twists the head!
2017-07-08 20:43:38.5437|FATAL|SoundCenSeGTK.FmodChannelPool|sf.SoundSoundFile.SoundFile is NULL while looking for F:\Games\Dwarf Fortress\PeridexisErrant's Starter Pack 0.43.05-r07\LNP\Utilities\Soundsense\packs\battle\gore/glance1.mp3
2017-07-08 20:43:38.5787|FATAL|SoundCenSeGTK.FmodChannelPool|sf.SoundSoundFile.SoundFile is NULL while looking for F:\Games\Dwarf Fortress\PeridexisErrant's Starter Pack 0.43.05-r07\LNP\Utilities\Soundsense\packs\battle\hit/ranged/arrowHit02.mp3
2017-07-08 20:43:38.6042|WARN|missing|The force pulls the head!
2017-07-08 20:43:39.0007|FATAL|SoundCenSeGTK.FmodChannelPool|sf.SoundSoundFile.SoundFile is NULL while looking for F:\Games\Dwarf Fortress\PeridexisErrant's Starter Pack 0.43.05-r07\LNP\Utilities\Soundsense\packs\battle\gore/tearheavygore1.mp3
2017-07-08 20:43:39.0222|FATAL|SoundCenSeGTK.FmodChannelPool|sf.SoundSoundFile.SoundFile is NULL while looking for F:\Games\Dwarf Fortress\PeridexisErrant's Starter Pack 0.43.05-r07\LNP\Utilities\Soundsense\packs\battle\hit/ranged/arrowHit06.mp3
2017-07-08 20:43:40.2912|FATAL|SoundCenSeGTK.FmodChannelPool|sf.SoundSoundFile.SoundFile is NULL while looking for F:\Games\Dwarf Fortress\PeridexisErrant's Starter Pack 0.43.05-r07\LNP\Utilities\Soundsense\packs\battle\gore/tearheavygore2.mp3
2017-07-08 20:43:40.3142|FATAL|SoundCenSeGTK.FmodChannelPool|sf.SoundSoundFile.SoundFile is NULL while looking for F:\Games\Dwarf Fortress\PeridexisErrant's Starter Pack 0.43.05-r07\LNP\Utilities\Soundsense\packs\battle\hit/ranged/arrowHit05.mp3
2017-07-08 20:43:40.8492|FATAL|SoundCenSeGTK.FmodChannelPool|sf.SoundSoundFile.SoundFile is NULL while looking for F:\Games\Dwarf Fortress\PeridexisErrant's Starter Pack 0.43.05-r07\LNP\Utilities\Soundsense\packs\battle\gore/tearheavygore7.mp3
2017-07-08 20:43:40.8492|FATAL|SoundCenSeGTK.FmodChannelPool|sf.SoundSoundFile.SoundFile is NULL while looking for F:\Games\Dwarf Fortress\PeridexisErrant's Starter Pack 0.43.05-r07\LNP\Utilities\Soundsense\packs\battle\gore/tearheavygore7.mp3
2017-07-08 20:43:40.8847|FATAL|SoundCenSeGTK.FmodChannelPool|sf.SoundSoundFile.SoundFile is NULL while looking for F:\Games\Dwarf Fortress\PeridexisErrant's Starter Pack 0.43.05-r07\LNP\Utilities\Soundsense\packs\battle\hit/ranged/arrowHit08.mp3`

**Comment by Algorithman** [comment] 2017-07-08 18:48
i wonder if i can provoke fights to check this

**Comment by thmsndk** [comment] 2017-07-08 18:51
It is a hunter running around hunting I think, as you can see in the log it is arrowHit, the first one is tearHeavyGore thought, who knows if you can provoke fights to check it :) 

If you can't reproduce it on your end, I can still test things for you :)

**Comment by Algorithman** [comment] 2017-07-08 19:00
Hmm, i get lock race now i think, program get unresponding after a fight

**Comment by Algorithman** [comment] 2017-07-08 19:02
and the fighting sounds are actually played as SFX, not battle sounds

**Comment by Algorithman** [comment] 2017-07-08 19:14
maybe a dumb question, but did you download all sound files?

**Comment by Algorithman** [comment] 2017-07-08 19:15
nvm, i got the problem now. most likely that disabled sounds lead to this error

**Comment by thmsndk** [comment] 2017-07-08 19:18
@Algorithman no clue if I downloaded them all, I pressed the update/install button after installing it :)
Afaik I have not disabled any sounds myself, and my log keeps getting FATAL entries, it appears to no resolve itself, but I do have multiple hunters hunting all the time :)

**Comment by Algorithman** [comment] 2017-07-08 19:24
does it actually play these sounds?

**Comment by Algorithman** [comment] 2017-07-08 19:28
it's thread concurrency, not the disabled sounds. already disposed objects in list to check. 
i remove the FATAL log entries, since it doesnt crash anymore

**Comment by thmsndk** [comment] 2017-07-08 19:28
It updates the UI with the sound, I think it actually plays the sound aswell, but it is a little hard to distinguish :P
![image](https://user-images.githubusercontent.com/9084377/27988535-fc1b009a-6423-11e7-95d8-c1a1a0466ada.png)

**Comment by Algorithman** [comment] 2017-07-08 19:42
Uploaded new version now: https://github.com/Algorithman/SoundCenSe/releases/tag/1.4.3
same as last, just without the log fillers

**Comment by Algorithman** [comment] 2017-07-08 19:49
I leave this issue open for a few more days, if you encounter any more crashes, pls gimme a shout :)

**Comment by thmsndk** [comment] 2017-07-08 19:56
@Algorithman Will do, I installed the new version aswell, thanks for fixing it! <3

**Comment by Algorithman** [comment] 2017-07-08 19:56
you're very welcome, testsubject :)

SCNR

**Comment by thmsndk** [comment] 2017-07-09 02:34
So I finally got sieged by a bunch of goblins, "huge" fight started and SoundCense ended up with (Not Responding) in the start I could not focus (alt+tab) the GUI at all, now I can focus it, but it is unresponsive. it has not crashed yet, but i'm guessing I have to force shutdown the application.

**Comment by Algorithman** [comment] 2017-07-09 04:01
Yeah, if too much is going on, it clogs up. Seems it's something with the Threshold values. I'll check it.

**Comment by Algorithman** [comment] 2017-07-09 08:50
added a new version, should fix the freezes. If you want, i have a small test program (which fills your gamelog.txt with lines, to stress test SoundCenSe. Since Win10 has a different threading model, it would be great to get some feedback. (i added it to the 1.4.4 release)

**Comment by thmsndk** [comment] 2017-07-09 09:18
Sure, I can test it out, I'll do it sometime later today when I have more time :) 

Thanks for an awesome program, I love that the different sounds has different channels :)

**Comment by thmsndk** [comment] 2017-07-09 10:49
@Algorithman Tried the stresser with v 1.4.3, it promply "crashed" and went into a not responding state.
Ran it again with 1.4.4 and everything played and responded fine 👍

**Comment by Algorithman** [comment] 2017-07-09 10:55
As expected :)
Thx for testing, closing this issue now

**Closed by Algorithman** 2017-07-09 10:55 UTC
